/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as SymbolIndexRouteImport } from './routes/symbol/index'

const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolIndexRoute = SymbolIndexRouteImport.update({
  id: '/symbol/',
  path: '/symbol/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/design-system': typeof DesignSystemRoute
  '/symbol/': typeof SymbolIndexRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/symbol': typeof SymbolIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/design-system': typeof DesignSystemRoute
  '/symbol/': typeof SymbolIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/design-system' | '/symbol/'
  fileRoutesByTo: FileRoutesByTo
  to: '/design-system' | '/symbol'
  id: '__root__' | '/design-system' | '/symbol/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DesignSystemRoute: typeof DesignSystemRoute
  SymbolIndexRoute: typeof SymbolIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbol/': {
      id: '/symbol/'
      path: '/symbol'
      fullPath: '/symbol/'
      preLoaderRoute: typeof SymbolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DesignSystemRoute: DesignSystemRoute,
  SymbolIndexRoute: SymbolIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
